trigger:
  branches:
    include:
    - master
    - releases/*
    
resources:
- repo: self

pool:
  vmImage: 'Ubuntu 18.04'

variables:
  buildConfiguration: 'Release'
  ngBuildConfiguration: '--prod'

steps:

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install
    workingDir: src/angular7

#- task: Npm@1
#  displayName: 'Build Angular'
#  inputs:
#    command: custom
#    customCommand: run build -- $(ngBuildConfiguration)
#    workingDir: src/angular7

- task: Npm@1
  displayName: 'Test Angular'
  inputs:
    command: 'custom'
    workingDir: '$(Build.SourcesDirectory)/src/angular7'
    customCommand: 'run test -- --watch=false --code-coverage'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage Angular results'
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: 'src/coverage/cobertura-coverage.xml'
    reportDirectory: src/coverage
    failIfCoverageEmpty: true

